### ISSUE TITLE
Add the ability to set the remote and the local recording frequency

### ISSUE THREAD

**Issue by GrazianoCapelli** [BasicAirData/AirDataBridge#2]
Two settings should be added in order to set the two recording frequencies.
The real time data update rate, when enabled, will follow the local recording frequency.

In case, can we evaluate the possibility to set the serial frequency too?

**Comment by JLJu** [comment]
The serial frequency over BT should be matched with ADC BT module frequency. An automatic function is not a priority, so I rather leave that part to future enhancement :-)

**Comment by GrazianoCapelli** [comment]
I agree about the Baud rate.
In fact the setting will set the $DTA Bluetooth frequency, and not the baud rate.
